// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX7S9b8iTHRtnZj46XOmCOmOJrhQIN7-U',
    appId: '1:189026039486:web:0b728952b1d0a29f49d0ef',
    messagingSenderId: '189026039486',
    projectId: 'health-improvement-4a8c6',
    authDomain: 'health-improvement-4a8c6.firebaseapp.com',
    storageBucket: 'health-improvement-4a8c6.appspot.com',
    measurementId: 'G-XX0M2Q30GE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5iqvoVLQODoyqG0OBXO9HiDwAND303j4',
    appId: '1:189026039486:android:411c8b7726afeb1749d0ef',
    messagingSenderId: '189026039486',
    projectId: 'health-improvement-4a8c6',
    storageBucket: 'health-improvement-4a8c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATK9wOSEjhEHkdmlT7xL8ATUVKoA1AeUQ',
    appId: '1:189026039486:ios:f981e2936bfecfc149d0ef',
    messagingSenderId: '189026039486',
    projectId: 'health-improvement-4a8c6',
    storageBucket: 'health-improvement-4a8c6.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATK9wOSEjhEHkdmlT7xL8ATUVKoA1AeUQ',
    appId: '1:189026039486:ios:b05dea60ea7231ed49d0ef',
    messagingSenderId: '189026039486',
    projectId: 'health-improvement-4a8c6',
    storageBucket: 'health-improvement-4a8c6.appspot.com',
    iosBundleId: 'com.example.untitled.RunnerTests',
  );
}
